# Generated by Django 3.2.13 on 2022-10-06 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
