# Generated by Django 3.2.13 on 2022-10-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_pk',
            new_name='user',
        ),
    ]
