# Generated by Django 3.2.13 on 2022-10-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20221019_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='media'),
        ),
    ]
