# Generated by Django 3.2.13 on 2022-10-10 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.TextField()),
                ('team_name', models.CharField(max_length=60)),
                ('logo', models.ImageField(blank=True, upload_to='image/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('content', models.TextField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(blank=True, upload_to='image/uniform')),
                ('team_pk', models.ForeignKey(db_column='team_pk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.team')),
            ],
        ),
    ]
