# Generated by Django 3.2.13 on 2022-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
