# Generated by Django 3.2.13 on 2022-10-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='no_img.png', upload_to='image/article_image'),
        ),
    ]
