# Generated by Django 3.2.13 on 2022-10-24 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_like',
            field=models.ManyToManyField(related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
