# Generated by Django 3.2.13 on 2022-10-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='no_profile_pic.png', upload_to='profile_pic'),
        ),
    ]
